### ISSUE TITLE
Reduce number of database requests

### ISSUE THREAD

**Issue by jdbit** [comments-ink/django-comments-ink#46]
Hi,
I don't use pagination for comments, so when I load 100 comments under a post, it makes 100+ additional requests to the database when trying to get reactions for each comment in a separate request. Is there any way to reduce the number of DB requests? I thought about select_related, but it looks like InkComment model has no relation with CommentReaction. Thanks!

**Comment by danirus** [comment]
Hi @jdbit, the first time the page is visited it runs the queries and it caches the results. From then on it uses the cached results, so following visits don't trigger that many queries. You can see that in the sample projects [dci-project-quotes](https://github.com/comments-ink/dci-project-quotes) and [dci-project-stories](https://github.com/comments-ink/dci-project-stories).

**Comment by jdbit** [comment]
I noticed that it uses cache, but somehow render time is still slower compared to XtdComments with the same 100 comments. Maybe it's something related to template rendering time or some Django settings I use, I'll try to figure out. Thank you!

**Comment by jdbit** [comment]
Hi @danirus, as far as I understand, the problem is in the cache of replies count. As you can see on the screenshot, Django spends 0.7 seconds loading the Redis cache (more than 200 calls, for ~100 comments).

![Screenshot from 2022-09-29 20-50-30](https://user-images.githubusercontent.com/3685801/193118050-b0c53298-4408-4aac-a31b-3cf06215a3b4.png)

I've removed this chunk from `comment.html` template and now the page loads much faster:

```
{% if comment.level == 0 and comment.nested_count and not comment.is_removed %}
                <span class="text-muted">
                    <span id="comment-{{ comment.id}}-replies" data-dci="nreplies" data-comment="{{ comment.id }}" class="small">{% blocktrans count replies=comment.nested_count%}One reply{% plural %}{{ replies }} replies{% endblocktrans %}</span>
                    {% if cfold|has_comment:comment %}<a href="?{% render_qs_params unfold comment %}#{{ anchor }}" class="small text-decoration-none">&mapstoup;</a>{% else %}<a href="?{% render_qs_params fold comment %}#{{ anchor }}" class="small text-decoration-none">&mapstodown;</a>{% endif %}
                </span>
                {% elif comment.level != 0 and comment.nested_count and not comment.is_removed %}
                <span class="text-muted">
                    <span id="comment-{{ comment.id}}-replies" data-dci="nreplies" data-comment="{{ comment.id }}" class="small">{% blocktrans count replies=comment.nested_count%}One reply{% plural %}{{ replies }} replies{% endblocktrans %}</span>
                    <a href="#" id="fold-{{ comment.id}}" data-dci-action="fold" data-dci-replies="{{ comment.nested_count }}" class="d-none">&mapstodown;</a><a href="#" id="unfold-{{ comment.id}}" data-dci-action="unfold" data-dci-replies="{{ comment.nested_count }}" class="d-none">&mapstoup;</a>
                </span>
                {% endif %}
```

**Comment by danirus** [comment]
Thanks for your comment @jdbit. Just as a quick comparison, using the dci-project-quotes, which uses the file system cache backend, it makes 73 calls in 17.33 ms. It's known that the file system is faster than Redis, that is expected, but your Redis is over 10 times slower than the filesystem in this case.

The caching I do is very low level, as you see there, on per comment ID. Maybe it could be done at a higher level, saving the whole chunk of comments for a given content_type and object_pk. It's really worth considering. Thank you for sharing.

**Comment by jdbit** [comment]
Thank you @danirus! Didn't know Redis is slower, maybe I should move to the filesystem cache in this case.

**Comment by danirus** [comment]
Sorry, I was wrong. Those numbers come from using the `LocMemCache`, the Django cache that uses only local memory. That's why it is faster.
