### ISSUE TITLE
reaction counter when clicking on existing reactions

### ISSUE THREAD

**Issue by ogurec-ogurec** [comments-ink/django-comments-ink#54]
Please tell how you can make a reaction to a comment click when you click on an existing one reactions:

![image](https://github.com/comments-ink/django-comments-ink/assets/66796268/9a44f72b-e0be-4f99-b5e1-287031fbc519)
That is, we do not click on the reaction in the pop-up window and it is added to the existing ones, but we click on the existing one and the counter increases. (example as in Telegram posts). How can I do this? @danirus

This is currently implemented **_(Reactions at post)_** at [dci-project-stories](https://github.com/comments-ink/dci-project-stories) 
`COMMENTS_INK_OBJECT_REACTIONS_ENUM`

**Comment by danirus** [comment]
Sorry @ogurec-ogurec, I don't have time to work on this application.
